@startuml
scale 600 height
!include skatt.iuml
skinparam  BackgroundColor white






component is [
ImageStream
--
name=app
version=1.3.0-b1.18.1-wingnut11-1.4.0
]

component dc [
DeploymentConfig
--
name=app
spec/image=app:sha256....
]

storage app [
app
---
1.3.0-b1.18.1-wingnut11-1.4.0
]

is --> app : scheduled import
is --> dc :  update image


@enduml