@startuml
scale 600 height
!include skatt.iuml
skinparam  BackgroundColor white

() findEvents as " "

package ImageChangeEvent [
 registry=docker.skatteetaten.no
 name=no.skatteetaten.demo/whoami
 tag=1
]

rectangle DeploymentConfig [
 DeploymentConfig
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]
component ImageStream [
 ImageStream
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]
rectangle Sprocket [
 Sprocket
 ---
  skatteetaten.no/sprocket=sha1-abcdefg
 ---
 spec:
 - kind: BuildConfig
 - name: app
 - namespace: env
]

rectangle BuildConfig [
 BuildConfig
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

rectangle Deployment [
 Deployment
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]


ImageChangeEvent --> findEvents : sha1-abcdefg
findEvents --> DeploymentConfig
findEvents -right-> Deployment
findEvents -left-> ImageStream
findEvents --> Sprocket
findEvents --> BuildConfig











@enduml