@startuml
!include skatt.iuml
scale 700 height


database Nexus [
Nexus
---
file:app-1.3.0-Leveransepakke.zip
]



storage  architect [
aurora/architect
---
version=1.18.1
role=CustomBuilder
]

storage wingnut11 [
aurora/wingnut11
---
version=1.4.0
role=BaseImage
]


component BuildConfig [
BuildConfig
--
name=app
version=1.3.0
]


storage app [
app
---
sha256:d72 latest
sha256:d72 1
sha256:d72 1.3
sha256:d72 1.3.0
sha256:d72 1.3.0-b1.18.1-wingnut11-1.4.0
--
sha256:c4d 1.2
sha256:c4d 1.2.3
sha256:c4d 1.2.3-b1.18.1-wingnut11-1.4.0
sha256:a1b 1.2.3-b1.18.1-wingnut11-1.3.1
]


architect -up-> Nexus : fetches zip
architect --> wingnut11 : FROM
BuildConfig -down-> architect: trigger on change
BuildConfig --> wingnut11: trigger on change
architect --> app : produce digest d72

@enduml