@startuml
scale 600 height
!include skatt.iuml
skinparam  BackgroundColor white






component is [
ImageStream
--
name=app
tags
 - from/name=docker.registry/app:1
 - name=default
 - scheduled=true
]

component dc [
DeploymentConfig
--
name=app
spec/image=docker.registry/app@sha256:c4d
]

storage app [
app
---
sha256:c4d 1
]

component rc [
RepllicationController
--
app-2
]

rectangle pod [
Pod
--
app-2-12ab
aurora_version= 1.2.3-b1.18.1-wingnut11-1.4.0
]

is --> app : scheduled import
is --> dc :  update spec/image
dc --> rc : rollout
rc -right-> pod : start



@enduml