@startuml
!include skatt.iuml


component ImageChangeEvent [
ImageChangeEvent
--
 pullRegistry=internal-private-pull
 name=no.skatteetaten.demo/whoami
 tag=1
 digest=sha256:a1b
 sprocketLabel=sha1-a1b2adf
 source= Nexus
]

folder Config {
artifact registry [
ImageChangeEventSource
--
type: Nexus|Docker|Generic
authType: HMAC|Bearer
url: http://push-url
pullUrls: pull-url1, pull-url2
]

artifact cluster [
Cluster
--
name: utv
url: http://
token: aldkfja
]

artifact resource [
Resource
--
kind: BuildConfig\n         Deployment\n         Job
]

resource *-left-* cluster : ClusterResource

artifact hook [
Hook
--
eventType: "onImageChangeEvent | onUpdate"
url: http://foo.bar
authType: Bearer
token: aldfjaflkj
type: notary
]
}


component AffectedResource [
AffectedResource
--
 requiresApprovalFrom: ROLE1, ROLE2
 status: Registered|deployed|rejected
 lastUpdated: <date>
]

rectangle hookResult [
HookResult
---
status: Success
message: Foo
link: http://...
]

ImageChangeEvent --* hookResult : hooks

AffectedResource --* hookResult :  hooks

AffectedResource *-right-- ImageChangeEvent: is affected by
AffectedResource *-up- resource : resource type
AffectedResource *-up- cluster : is in cluster
ImageChangeEvent *-- registry: source

hook --* hookResult : type
@enduml