@startuml
scale 700 height
!include skatt.iuml



database vanilla [
DockerRegistry
]

database DockerRegistry [
Nexus
]

interface ExternalProvider


interface ExternalService

rectangle ImageChangeEventParser<<node>>
database ImageChangeEvents<<sprocket>>

rectangle ResourceFetcher<<node>>

ExternalProvider --> ImageChangeEventParser : 1. Send CloudEvent
DockerRegistry --> ImageChangeEventParser : 1.Send audit events
vanilla --> ImageChangeEventParser : 1.Send audit events
ImageChangeEventParser --> ImageChangeEvents : 3. Store
ImageChangeEventParser -right-> ResourceFetcher : 4. fetch resources
ImageChangeEventParser -left-> ExternalService : 2.  webhook


@enduml