@startuml
!include skatt.iuml
scale 700 height


database KubernetesU<<kubernetes>> [
utv
]

database KubernetesT<<kubernetes>> [
prod
]


interface ChatUser
rectangle ResourceFetcher<<node>>

database AffectedResources<<sprocket>>
queue ResourceQueue<<sprocket>>


ResourceFetcher -up-> KubernetesU : 2. fetch resources
ResourceFetcher -up-> KubernetesT : 2. fetch resources
ResourceFetcher -right-> AffectedResources : 3. store
ResourceFetcher --> ResourceQueue : 4. add to queue if not present
ResourceFetcher --> ChatUser: 4. ask for approval

@enduml