@startuml
scale 900 height
!include skatt.iuml





database NexusDockerRegistry
rectangle Sprocket

database utv<<kubernetes>>


NexusDockerRegistry --> Sprocket : 1.Send audit events
Sprocket --> utv: 2. find resources and update resources




@enduml