@startuml
!include skatt.iuml






database KubernetesP<<kubernetes>> [
prod
]

database KubernetesU<<kubernetes>> [
utv
]

rectangle BuildPartition<<leader>>
rectangle DeployProdPartition<<leader>>
rectangle DeployUtvPartition<<leader>>

queue ResourceQueue<<sprocket>>

interface ExternalService

BuildPartition -left-> ResourceQueue : 1.fetch 10\n wait 30
BuildPartition -up-> KubernetesU : 2. start builds

DeployProdPartition -up-> ResourceQueue : 1. fetch 20\n wait 10
DeployProdPartition -left-> ExternalService: 2. onUpdateHook
DeployProdPartition -right-> KubernetesP : 3. deploy


DeployUtvPartition -right-> ResourceQueue : 1. fetch 50\n wait 20
DeployUtvPartition -up-> KubernetesU : 2. deploy

@enduml