@startuml
!include skatt.iuml



database vanilla [
DockerRegistry
]

database DockerRegistry [
Nexus
]

interface ExternalProvider


interface ExternalService

rectangle ImageChangeEventParser<<node>>
database ImageChangeEvents<<sprocket>>

rectangle ResourceFetcher<<node>>

ExternalProvider --> ImageChangeEventParser : 1.  CloudEvent
DockerRegistry --> ImageChangeEventParser : 1.audit events
vanilla --> ImageChangeEventParser : 1.audit events
ImageChangeEventParser --> ImageChangeEvents : 3. Store
ImageChangeEventParser -down-> ResourceFetcher : 4. fetch resources
ImageChangeEventParser -left-> ExternalService : 2.  webhook


@enduml