@startuml
!include skatt.iuml
scale 1000 height

() findEvents as " "

package ImageChangeEvent [
 registry=docker.skatteetaten.no
 name=no.skatteetaten.demo/whoami
 tag=1
 digest=sha256:a1b
 sprocketLabel=sha1-a1b2adf
]


component ImageStream<<MVP>>[
 ImageStream
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

component BuildConfig [
 BuildConfig
 Job
 ---
 skatteetaten.no/sprocket=sha1-abcdefgJob
]


component Deployment [
 Deployment
 DemonSet
 StatefulSet
 ---
  skatteetaten.no/sprocket=sha1-abcdefg
]


ImageChangeEvent -down-> findEvents : sha1-abcdefg
findEvents --> Deployment
findEvents -left-> ImageStream
findEvents -right-> BuildConfig











@enduml