@startuml
!include skatt.iuml

() findEvents as " "

package ImageChangeEvent [
 registry=docker.skatteetaten.no
 name=no.skatteetaten.demo/whoami
 tag=1
 digest=sha256:a1b
 sprocketLabel=sha1-a1b2adf
]


component ImageStream<<MVP>>[
 ImageStream
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

component BuildConfig [
 BuildConfig
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]


component Job [
 Job
 --
 skatteetaten.no/sprocket=sha1-abcdefg
]
component Deployment [
 Deployment
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

component DemonSet [
 DemonSet
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

component StatefulSet [
 StatefulSet
 ---
 skatteetaten.no/sprocket=sha1-abcdefg
]

ImageChangeEvent -right-> findEvents : sha1-abcdefg
findEvents -up-> Deployment
findEvents -up-> DemonSet
findEvents -up-> StatefulSet
findEvents -right-> ImageStream
findEvents --> Job
findEvents --> BuildConfig











@enduml