@startuml
!include skatt.iuml
scale 700 height




database NexusDockerRegistry
rectangle Sprocket

database utv<<kubernetes>>


NexusDockerRegistry --> Sprocket : 1.Send audit events
Sprocket --> utv: 2. find resources\n 3. update resrouces




@enduml