= Introduksjon til Spring Boot, notater

== Hva er Spring Boot?

Spring Boot er et rammeverk som gjør det lett å lage *stand-alone*, Springbaserte produksjonsapplikasjoner.

Har sterke meninger, populært kalt konvensjoner, i forhold til bruk av Spring og tredjepartsbiblioteker - både hvilke og hvordan de brukes. De fleste Spring Boot applikasjoner trenger lite konfigurasjon.

I sin enkleste form er spring boot automatisk konfigurasjon av applikasjonen
med basic spring features som DI container og oppsett av logging. Man kan utvide applikasjonens funksjonalitet ved å
trekke inn flere spring-moduler (kalt startere) som automatisk plukkes opp basert på konvensjoner og utvider
applikasjonens funksjonalitet.

Startere: eksempel; webapplikasjon; spring-boot-starter-web får da avhengigheter til servletcontainer, webrammeverk, json-parser osv.
Database; spring-boot-starter-jdbc, springavhengigheter + datasourceimplementasjon

Auto-configuration er ikke-inasiv. Du kan når som helst definere din egen konfigurasjon for å erstatte deler av auto-konfigurasjonen. For eksempel, dersom du legge til din egen DataSource trekker defaulten fra Spring seg automatisk bort.

== Spring og Spring Boot Basics

* En enkel spring boot applikasjon. Hva får man? (start.spring.io)
* Åpne i IntelliJ og vis hva vi har fått
** Slette tester
** pom.xml med spring boot plugin og avhengighet
** maven plugin, nevne at vi får byggeoppsett derfra.
** parent, vise at vi får versjoner derfra.
* Se på dependencies
* Kjør fra kommandolinje;

    ./mvnw spring-boot:run

    ./mvnw package
    ls -altrh target/
    unzip -l target/demo-0.0.1-SNAPSHOT.jar | less
    java -jar target/demo-0.0.1-SNAPSHOT.jar

* Kjør fra IntelliJ
* Classpath scanning (auto configuration).
* DI
** Implements CommandLineRunner. Sout hello.
** Lage GreetingService med getGreeting(). Instansiere i DemoApplication.
** Fjerne new. Lage constructor. @Component på GreetingService.
** Vise field injection, setter-injection og constructor injection.

* Konfigurasjon
** Konfigurere applikasjon
** application.properties
** Konfigurere spring (spring.main.banner-mode=off)
** Gjøre greeting konfigurerbar via property.
** Defaultverdi
** overrides via system properties og miljøvariable

    java -Dgreeting=Hei -jar target/demo-0.0.1-SNAPSHOT.jar

    export GREETING=Hei
    java -jar target/demo-0.0.1-SNAPSHOT.jar
    set -e GREETING

** profiler (engelsk og norsk profil)
*** Bytte til application.yml
*** Lage profile for nor

[source,yml]
----
include::{examples}/demo-simple/src/main/resources/application.yml[]
----


*** Vise fra kommandolinje

    java -jar -Dspring.profiles.active=nor target/demo-0.0.1-SNAPSHOT.jar
    export SPRING_PROFILES_ACTIVE=nor
    java -jar target/demo-0.0.1-SNAPSHOT.jar
    set -e SPRING_PROFILES_ACTIVE
    java -jar target/demo-0.0.1-SNAPSHOT.jar

[source,java]
----
include::{examples}/demo-simple/src/main/java/com/example/demo/GreetingService.java[]
----

* Logging
** Legge på logger og forklare defaultoppsettet
** Konfigurerer logging basert på innholdet på classpathen. Defaulten er logback og kommer med spring-boot-starter.
** Konfigurere logging (logging.level.com.example.demo = DEBUG)

  logging:
    level:
      com:
        example:
          demo: INFO

** Vise fra kommandolinje:

  java -jar -Dlogging.level.com.example.demo=DEBUG target/demo-0.0.1-SNAPSHOT.jar

** Vis at det ikke går via miljøvariabel, samt vise alternativ løsning.

  log:
    demo: DEBUG

  logging:
    level:
      com:
        example:
          demo: ${log.demo}


== Spring MVC
* Man deployet tidligere applikasjoner som war filer i en servlet container


== Webapplikasjon

* start.sping.io med web (ta bort tester)
* vise avhengigheter (kommentere jackson, hibernate-validator, tomcat og spring-webmvc)
* Kjør

    ./mvnw clean package
    java -jar target/demo-web-0.0.1-SNAPSHOT.jar

* Hva får vi ut av boksen?
** Applikasjon med embedded tomcat som starter ferdig konfigurert (port 8080)
** Basic content-negotiation

    Chrome http://localhost:8080
    http --verbose :8080
    http --verbose :8080 Accept:text/html

** Default port 8080 (kan overrides) export SERVER_PORT=9090 server.port=9090
** Gå gjennom basic hello world -> request param -> json response -> date property (ISO 8601)

[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/HelloWorld.java[]
----

** Post @RequestBody Map -> UpdateGreeterPayload -> @Valid med @NotNull og @Pattern(regexp = "[A-z\\s]+")

    http --verbose ":8080/greet?name=Bent"
    http --verbose ":8080/greeter" greeter=Espen
    echo '{}' | http --verbose ":8080/greeter"

[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/GreetingController.java[]
----

[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/GreetingService.java[]
----

** Generell error handling

    echo '{}' | http --verbose ":8080/greeter"

[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/ErrorHandler.java[]
----

** Kalle ekstern tjeneste
[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/ExternalServiceController.java[]
----

[source,java]
----
include::{examples}/demo-web/src/main/java/com/example/demoweb/ApplicationConfiguration.java[]
----


== Caching
* Legg på
[source,xml]
----
include::{examples}/demo-webcache/pom.xml[tag=dep-cache,indent=0]
----
[source,java]
----
include::{examples}/demo-webcache/src/main/java/com/example/demowebcache/DemoWebcacheApplication.java[]
----

[source,java]
----
include::{examples}/demo-webcache/src/main/java/com/example/demowebcache/GreetingController.java[]
----

    time http --verbose :8080/greet?name=Bent
    http --verbose :8080/greeter greeter=Espen


* Påpek problem med at cachen forsvinner etter restart og problem med multiple instanser
* Ta inn redis i pom.xml
[source,xml]
----
include::{examples}/demo-webcache/pom.xml[tag=dep-redis,indent=0]
----

  docker run -p 6379:6379 --rm --name redis redis
  docker run -it --link redis:redis --rm redis redis-cli -h redis -p 6379
  keys *
  get <key>


== JDBC
* starte postgres via Docker:

  docker run --rm --name postgres -e POSTGRES_PASSWORD=123dev -d -p 5432:5432 postgres

* Koble til db i IntelliJ
* Legge inn noe testdata:
[source,sql]
----
include::{examples}/demo-webjdbc/src/main/resources/db/migration/V201803021300__create_contact_table_with_data.sql[]
----
* Skriv initiell kodestruktur med controller og service (uten JdbcTemplate)
* Legg på starter jdbc
[source,java]
----
include::{examples}/demo-webjdbc/pom.xml[tag=dep-sb-jdbc,indent=0]
----
* Skriv initiell kode med JdbcTemplate og start applikasjonen. Kommenter feilene.
* Legge på JDBC driver
[source,java]
----
include::{examples}/demo-webjdbc/pom.xml[tag=dep-jdbc,indent=0]
----
* Legg inn config i application.properties
[source]
----
include::{examples}/demo-webjdbc/src/main/resources/application.properties[]
----
* Fullfør kodeeksempel
[source,java]
----
include::{examples}/demo-webjdbc/src/main/java/com/example/demowebjdbc/ContactController.java[]
----

  http ":8080/contact/
  http ":8080/contact/" firstName=Espen lastName=Strømland email=Espen.Stromland@skatteetaten.no


== Migreringer
* Migrations; legg på avhengighet i pom.xml

[source,java]
----
include::{examples}/demo-webjdbc/pom.xml[tag=dep-flyway,indent=0]
----

* Slett gamle tabeller
* Lag migrering i src/main/resources/db/migration/V201803021300__create_contact_table_with_data.sql

* Vis flyway_schema_history


== JPA
* Legg på avhengighet
[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=dep-jpa,indent=0]
----

* Sett property for å unngå feilmelding i loggen
[source]
----
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
----

[source,java]
----
include::{examples}/demo-webjpa/src/main/java/com/example/demowebjpa/ContactController.java[]
----


== Testing ==

* Nevne at det kan være greit å ikke bruke spring til testing
[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=dep-test,indent=0]
----
* Vise @SpringBootTest
* Vise hvordan man kan @Autowire inn objekter i testen.
* Databasetest: Legge til h2 og vise at applikasjonen starter opp med in-memory database automatisk. Demonstrere at @AutoConfigureTestDatabase(replace= AutoConfigureTestDatabase.Replace.NONE) kan brukes til å påvirke dette.
[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=dep-h2,indent=0]
----

* Redusere logging
** I src/test/resources/logback.xml
[source,xml]
----
include::{examples}/demo-webjpa/src/test/resources/logback.xml[]
----
** I /src/test/resources/application.properties
[source]
----
include::{examples}/demo-webjpa/src/test/resources/application.properties[]
----

=== Repository test

[source,java]
----
include::{examples}/demo-webjpa/src/test/java/com/example/demowebjpa/ContactRepositoryTest.java[]
----

=== Controller test

* Vise Controller test uten mocking med (1L som param)
* Vise @MockBean for ContactRepository

[source,java]
----
include::{examples}/demo-webjpa/src/test/java/com/example/demowebjpa/ContactControllerTest.java[]
----

=== WebMvc test

* To test whether Spring MVC controllers are working as expected, use the @WebMvcTest annotation. @WebMvcTest auto-configures the Spring MVC infrastructure and limits scanned beans to @Controller, @ControllerAdvice, @JsonComponent, Converter, GenericConverter, Filter, WebMvcConfigurer, and HandlerMethodArgumentResolver. Regular @Component beans are not scanned when using this annotation.

* Vise @WebMvcTest(ContactController.class)

[source,java]
----
include::{examples}/demo-webjpa/src/test/java/com/example/demowebjpa/ContactEndpointTest.java[]
----

=== RestClient

* Vise @RestClientTest

[source,java]
----
include::{examples}/demo-webjpa/src/test/java/com/example/demowebjpa/ExternalServiceControllerTest.java[]
----

echo_response.json

  {
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,nb;q=0.8",
      "Connection": "close",
      "Cookie": "_gauges_unique_month=1; _gauges_unique_year=1; _gauges_unique=1",
      "Host": "httpbin.org",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
    },
    "json": null,
    "method": "GET",
    "origin": "151.187.161.3",
    "url": "https://httpbin.org/anything/HEPP"
  }


== Actuator

* Legger på en hel del "produksjonstjenester" på applikasjonen for monitorering og management.

[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=dep-actuator,indent=0]
----

* Vise med lite info:

  http://localhost:8080/actuator
  http://localhost:8080/actuator/health

* Skru på full info:

  management.endpoint.health.show-details=always

  http://localhost:8080/actuator/health

* Vis info (ingen info)

  http://localhost:8080/actuator/info

* Legge på build info:

[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=plugin-sb,indent=0]
----
  http://localhost:8080/actuator/info

* Legge på git info:

[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=plugin-git,indent=0]
----

  git init
  git add .
  git commit -m "Initial import"

  http://localhost:8080/actuator/info

* Eksponer alle endepunkt:

  management.endpoints.web.exposure.include=*

  http://localhost:8080/actuator/env
  http://localhost:8080/actuator/flyway
  http://localhost:8080/actuator/httptrace

* Skru på logging

  logging.file=app.log

  http://localhost:8080/actuator/logfile

* Lage egen helsesjekk:

[source,java]
----
include::{examples}/demo-webjpa/src/main/java/com/example/demowebjpa/SchemaVersionHealthIndicator.java[]
----

* Legge på prometheus metrikker

[source,xml]
----
include::{examples}/demo-webjpa/pom.xml[tag=dep-prometheus,indent=0]
----

== Honourable mentions ==
* WebClient
* Spring security
* Spring cloud
